server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/kyc_database?createDatabaseIfNotExist=true
    username: root
    password: developer@@
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

####Stored procedures
customer:
  procedure:
   find:
        all: CREATE PROCEDURE findAllCustomers()
            BEGIN
               SELECT * FROM customer;
            END
        age:
          by:
            name: CREATE PROCEDURE findCustomerAgeByName(IN name VARCHAR(50),OUT age Integer)
                  BEGIN
                    SELECT customer.age into age  FROM customer WHERE customer.name = name;
                  END
        by:
          age: CREATE PROCEDURE findCustomersByAge(IN age INTEGER)
              BEGIN
                 SELECT * FROM kyc_database.customer WHERE customer.age=age;
              END
   by:
     surname: CREATE PROCEDURE findCustomberBySurname(INOUT surname VARCHAR(50))
       BEGIN
            SELECT customer.surname INTO surname  FROM  customer WHERE customer.surname=surname;
       END
   sum:
    promotion:
       points: CREATE PROCEDURE sumPromotionalPoints(OUT totalPoints VARCHAR(50))
               BEGIN
                  SELECT SUM(promotion_point) INTO totalPoints FROM customer;
               END

   alter:
     find:
       all:  ALTER PROCEDURE findAllCustomers
             SQL SECURITY INVOKER
             COMMENT 'This procedure returns all customers';


view:
  procedure:
    information: SELECT * FROM INFORMATION_SCHEMA.ROUTINES  WHERE ROUTINE_NAME = 'findAllCustomers'
                  AND ROUTINE_SCHEMA = 'kyc_database';

